import "./globals.css";
import type { Metadata } from "next";
import Nav from "@/components/Nav/Nav";
import { Poppins, Rosarivo } from "next/font/google";

const poppins = Poppins({
    subsets: ["latin"],
    variable: "--font-poppins",
    display: "swap",
    weight: "400",
});

const rosarivo = Rosarivo({
    subsets: ["latin"],
    variable: "--font-rosarivo",
    display: "swap",
    weight: "400",
});

export const metadata: Metadata = {
    title: "Dora Portfolio",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={`${poppins.variable} ${rosarivo.variable}`}>
                <Nav />
                {children}
            </body>
        </html>
    );
}
